package measurement;

import java.util.HashMap;

import network.Circuit;
import network.ControlPlane;
import network.Pair;
import request.RequestForConnection;
import simulationControl.Util;
import simulationControl.parsers.SimulationRequest;
import simulationControl.resultManagers.BitRateBlockingProbResultManager;

/**
 * This class represents the bitRate blocking probability metric (general, per pair, per bitRate, per pair / bitRate)
 * The metric represented by this class is associated with a load point and a replication
 * 
 * @author Iallen
 */
public class BitRateBlockingProbability extends Measurement {
	
	public final static String SEP = "-";
	
	// Overall blockage probability
	private double generalRequestedBitRate;
	private double generalBitRateBlockingProbability;
	private double bitRateBlockingByFragmentation;
    private double bitRateBlockingByLackTransmitters;
    private double bitRateBlockingByLackReceivers;
    private double bitRateBlockingByQoTN;
    private double bitRateBlockingByQoTO;
    private double bitRateBlockingByOther;
    private double bitRateBlockingByXt;
    private double bitRateBlockingByXtOther;
    
    // Block per core
    private int maxCoresByLinks;
    private HashMap<Integer, Double> requestedBitRatePerCore;
    private HashMap<Integer, Double> bitRateBlockPerCore;
	
	// Blocking probability per pair
	private HashMap<String, Double> requestedBitRatePerPair;
	private HashMap<String, Double> bitRateBlockedPerPair;
	
	// Blocking probability per bit rate
	private HashMap<Double, Double> requestedBitRatePerBW;
	private HashMap<Double, Double> bitRateBlockedPerBW;
	
	// Blocking probability per pair / bit rate
	private HashMap<String, HashMap<Double,Double>> requestedBitRatePairBR;
	private HashMap<String, HashMap<Double,Double>> bitRateBlockedPairBR;
	
	private Util util;

	/**
	 * Creates a new instance of BitRateBlockingProbability
	 * 
	 * @param loadPoint int
	 * @param rep int
	 */
	public BitRateBlockingProbability(int loadPoint, int rep, Util util){
		super(loadPoint, rep);
		
		this.util = util;
		// bandwidth blocking probability general
		this.generalRequestedBitRate = 0.0;
		this.generalBitRateBlockingProbability = 0.0;
		
		this.maxCoresByLinks = 0;
		this.requestedBitRatePerCore = new HashMap<>();
        this.bitRateBlockPerCore = new HashMap<>();

		this.requestedBitRatePerBW = new HashMap<>();
		this.bitRateBlockedPerBW = new HashMap<>();
		
		this.requestedBitRatePerPair = new HashMap<>();
		this.bitRateBlockedPerPair = new HashMap<>();
		
		this.requestedBitRatePairBR = new HashMap<>();
		this.bitRateBlockedPairBR = new HashMap<>();
		
		resultManager = new BitRateBlockingProbResultManager();
	}
	
	/**
	 * Adds a new observation of block or not a request
	 * 
	 * @param cp ControlPlane
	 * @param success boolean
	 * @param request RequestForConnection
	 */
	public void addNewObservation(ControlPlane cp, boolean success, RequestForConnection request){
		// Calculate the amount of band requested by the circuit
		Double time = request.getTimeOfFinalizeHours() - request.getTimeOfRequestHours();
		Double bitRate = time * request.getRequiredBitRate();
		
		StringBuilder sbPair = new StringBuilder();
		sbPair.append(request.getPair().getSource().getName());
		sbPair.append(SEP);
		sbPair.append(request.getPair().getDestination().getName());
		String pairName = sbPair.toString();
		
		// Increment generated general requisitions
		this.generalRequestedBitRate += bitRate;
		
		if(maxCoresByLinks == 0) {
        	maxCoresByLinks = cp.getMesh().maximumCoresByLinks();
        	
        	for(Integer core = 0; core < maxCoresByLinks; core++) {
        		this.bitRateBlockPerCore.put(core, 0.0);
        	}
        }
		
		// Increment requests generated by pair
		Double numReq = this.requestedBitRatePerPair.get(pairName);
		if(numReq==null) numReq=0.0;
		this.requestedBitRatePerPair.put(pairName, numReq+bitRate);			
		
		// Increment requests generated by bitRate
		numReq = this.requestedBitRatePerBW.get(request.getRequiredBitRate());
		if(numReq==null) numReq=0.0;
		this.requestedBitRatePerBW.put(request.getRequiredBitRate(), numReq+bitRate);			
		
		// Increment requests generated by pair / bitRate
		HashMap<Double,Double> gplb = this.requestedBitRatePairBR.get(pairName);
		if(gplb==null){
			gplb = new HashMap<>();
			this.requestedBitRatePairBR.put(pairName, gplb);
		}
		numReq = gplb.get(request.getRequiredBitRate());
		if(numReq==null) numReq=0.0;
		gplb.put(request.getRequiredBitRate(), numReq+bitRate);
		
		// Increment requests generated by core
		for (Circuit c: request.getCircuits()) {
			Double numReqCore = this.requestedBitRatePerCore.get(c.getIndexCore());
	        if (numReqCore == null) numReqCore = 0.0;
	        this.requestedBitRatePerCore.put(c.getIndexCore(), numReqCore + bitRate);
        }
		
		// If the request was blocked
		if(!success){
			// Increment blocked requests general
			this.generalBitRateBlockingProbability += bitRate;
			
			for (Circuit c: request.getCircuits()) {
				if(c.isWasBlocked()){//considers that only one circuit has been blocked
					switch(c.getBlockCause()){
						case Circuit.BY_LACK_TX:
							this.bitRateBlockingByLackTransmitters += bitRate;
							break;
						case Circuit.BY_LACK_RX:
							this.bitRateBlockingByLackReceivers += bitRate;
							break;
						case Circuit.BY_XTN:
							this.bitRateBlockingByXt += bitRate;
							break;
						case Circuit.BY_QOTN:
							this.bitRateBlockingByQoTN += bitRate;
							break;
						case Circuit.BY_XTO:
							this.bitRateBlockingByXtOther += bitRate;
							break;
						case Circuit.BY_QOTO:
							this.bitRateBlockingByQoTO += bitRate;
							break;
						case Circuit.BY_FRAGMENTATION:
							this.bitRateBlockingByFragmentation += bitRate;
							break;
						case Circuit.BY_OTHER:
							this.bitRateBlockingByOther += bitRate;
							break;
					}
					break;
				}
			}
			
			for (Circuit c: request.getCircuits()) {
                if(c.isWasBlocked()){ //considers that only one circuit has been blocked
                	
                	// Increment bitRate blocked per core
                    Double numBlockCore = this.bitRateBlockPerCore.get(c.getIndexCore());
                    if (numBlockCore == null) numBlockCore = 0.0;
                    this.bitRateBlockPerCore.put(c.getIndexCore(), numBlockCore + bitRate);
                    
                    break;
                }
            }
			
			// Increment blocked requests per pair
			Double numBlock = this.bitRateBlockedPerPair.get(pairName);
			if(numBlock==null) numBlock=0.0;
			this.bitRateBlockedPerPair.put(pairName, numBlock+bitRate);			
			
			// Increment blocked requests per bitRate
			numBlock = this.bitRateBlockedPerBW.get(request.getRequiredBitRate());
			if(numBlock==null) numBlock=0.0;
			this.bitRateBlockedPerBW.put(request.getRequiredBitRate(), numBlock+bitRate);			
			
			// Increment blocked request per pair / bitRate
			HashMap<Double,Double> bplb = this.bitRateBlockedPairBR.get(pairName);
			if(bplb==null){
				bplb = new HashMap<>();
				this.bitRateBlockedPairBR.put(pairName, bplb);
			}
			numBlock = bplb.get(request.getRequiredBitRate());
			if(numBlock==null) numBlock=0.0;
			bplb.put(request.getRequiredBitRate(), numBlock+bitRate);
		}
	}

	@Override
	public String getFileName() {
		return SimulationRequest.Result.FILE_BITRATE_BLOCKING_PROBABILITY;
	}

	/**
	 * Returns the probability of blocking the general bitRate on the network
	 * 
	 * @return double
	 */
	public double getProbBlockGeneral(){
		return (this.generalBitRateBlockingProbability / this.generalRequestedBitRate);
	}
	
	/**
	 * Returns total requested bitRate.
	 * @return
	 */
	public double getGeneralRequestedBitRate() {
		return generalRequestedBitRate;
	}
	/**
     * Returns the bitRate blocking probability due to fragmentation
     *
     * @return double
     */
    public double getBitRateBlockingByFragmentation() {
        return ( this.bitRateBlockingByFragmentation / this.generalRequestedBitRate);
    }

    /**
     * Returns the bitRate blocking probability due to lack of transmitters
     *
     * @return double
     */
    public double getBitRateBlockingByLackTx() {
        return (this.bitRateBlockingByLackTransmitters / this.generalRequestedBitRate);
    }

    /**
     * Returns the bitRate blocking probability due to lack of receivers
     *
     * @return double
     */
    public double getBitRateBlockingByLackRx() {
        return (this.bitRateBlockingByLackReceivers / this.generalRequestedBitRate);
    }
    
    
    /**
     * Returns the probability of bitRate blocking by QoTN
     *
     * @return double
     */
    public double getBitRateBlockingByQoTN() {
        return (this.bitRateBlockingByQoTN / this.generalRequestedBitRate);
    }
    
    /**
     * Returns the probability of bitRate blocking by QoTO
     *
     * @return double
     */
    public double getBitRateBlockingByQoTO() {
        return (this.bitRateBlockingByQoTO / this.generalRequestedBitRate);
    }
    
    /**
     * Returns the probability of bitRate blocking by other
     *
     * @return double
     */
    public double getBitRateBlockingByOther() {
        return (this.bitRateBlockingByOther / this.generalRequestedBitRate);
    }
    
    /**
     * Returns the probability of bitRate blocking by XT
     * 
     * @return double
     */
    public double getBitRateBlockingByXt() {
        return (this.bitRateBlockingByXt / this.generalRequestedBitRate);
    }
    
    /**
     * Returns the probability of bitRate blocking by XTO
     * 
     * @return double
     */
    public double getBitRateBlockingByXtOther() {
        return (this.bitRateBlockingByXtOther / this.generalRequestedBitRate);
    }

	/**
	 * Returns the bitRate blocking probability of a given pair
	 * 
	 * @param p Pair
	 * @return double
	 */
	public double getProbBlockPair(Pair p){
		double res;
		
		String source = p.getSource().getName();
		String destination = p.getDestination().getName();
		Double gen = this.requestedBitRatePerPair.get(source + SEP + destination);
		if(gen==null) return 0.0; // No requests generated for this pair
		
		Double block = this.bitRateBlockedPerPair.get(source + SEP + destination);
		if(block==null) block = 0.0;
		
		res = ((double) block / (double) gen);		
		
		return res;
	}

	/**
	 * Returns the bitRate blocking probability of a given bitRate
	 * 
	 * @param bw double
	 * @return double
	 */
	public double getProbBlockBitRate(double bw){
		double res;
		Double gen = this.requestedBitRatePerBW.get(bw);
		if(gen==null) return 0.0; // No requests generated for this pair
		
		Double block = this.bitRateBlockedPerBW.get(bw);
		if(block==null) block = 0.0;
		
		res = ((double) block / (double) gen);		
		
		return res;
	}

    /**
     * Returns the amount of bitRate blocked for a specific core
     * 
     * @param core Integer
     * @return doulbe
     */
    public double getProbBlockPerCore(Integer core){
    	double res;
    	
    	Double gen = this.requestedBitRatePerCore.get(core);
    	if(gen == null)
    		return 0.0; // No requests generated for this core
    	
        Double block = this.bitRateBlockPerCore.get(core);
        if(block == null)
        	block = 0.0;
        
        res = ((double) block / (double) gen);	
        
        return res;
	}
	
	/**
	 * Returns the bitRate blocking probability of a given bitRate in a given pair
	 * 
	 * @param p Pair
	 * @param bw double
	 * @return double
	 */
	public double getProbBlockPairBitRate(Pair p, double bw){
		double res;
		String or = p.getSource().getName();
		String dest = p.getDestination().getName();
		
		Double gen = null;
		if(this.requestedBitRatePairBR.get(or + SEP + dest) != null){
			gen = this.requestedBitRatePairBR.get(or + SEP + dest).get(bw);
		}
		
		if(gen == null) return 0.0; // No requests generated for this pair
		Double block = 0.0;
		
		HashMap<Double, Double> hashAux = this.bitRateBlockedPairBR.get(or + SEP + dest);
		if(hashAux==null || hashAux.get(bw)==null){
			block = 0.0;
		}else{
			block = hashAux.get(bw);
		}
		
		res = ((double) block / (double) gen);		
		
		return res;
	}

	/**
     * Returns the util
     * 
     * @return util
     */
    public Util getUtil() {
        return util;
    }

    /**
     * Returns the maximum number of cores between all links
     *
     * @return int
     */
    public int getMaxCoresByLinks() {
    	return maxCoresByLinks;
    }

}
