package measurement;

import java.util.HashMap;

import gprmcsa.powerAssignment.PABSAlgorithm;
import gprmcsa.powerAssignment.PABSAlgorithm_v2;
import network.Circuit;
import network.ControlPlane;
import network.Pair;
import request.RequestForConnection;
import simulationControl.Util;
import simulationControl.parsers.SimulationRequest;
import simulationControl.resultManagers.BlockingProbResultManager;

/**
 * This class represents the locking probability metric (general, per pair, per bandwidth, 
 * per pair / BandWidth)
 * The metric represented by this class is associated with a load point and a replication
 *
 * @author Iallen
 */
public class BlockingProbability extends Measurement {

    public final static String SEP = "-";

    // Overall blockage probability
    private int numGeneralGeneratedReq;
    private int numGeneralRegBlockProb;
    private int numReqBlockByFragmentation;
    private int numReqBlockByLackTransmitters;
    private int numReqBlockByLackReceivers;
    private int numRegBlockByQoTN;
    private int numRegBlockByQoTO;
    private int numRegBlockByOther;
    private int numRegBlockByXt;
    private int numRegBlockByXtOther;
    
    // Related to PABS power allocation algorithm
    private int numAttemptsCounter;
    private int numAttemptsQoTOCounter;
    
    // Block per core
    private int maxCoresByLinks;
    private HashMap<Integer, Integer> numReqGenPerCore;
    private HashMap<Integer, Integer> numBlockPerCore;
    
    // Blocking probability per pair
    private HashMap<String, Integer> numReqGenPair;
    private HashMap<String, Integer> numReqBlockPair;

    // Blocking probability per bandwidth
    private HashMap<Double, Integer> numReqGenBW;
    private HashMap<Double, Integer> numReqBlockBW;

    // Blocking probability per pair / BandWidth
    private HashMap<String, HashMap<Double, Integer>> numReqGenPairBW;
    private HashMap<String, HashMap<Double, Integer>> numReqBlockPairBW;

    private Util util;
    
    /**
     * Creates a new instance of BlockingProbability
     *  @param loadPoint int
     * @param rep int
     * @param util
     */
    public BlockingProbability(int loadPoint, int rep, Util util) {
        super(loadPoint, rep);
        
        this.util = util;
        this.numGeneralGeneratedReq = 0;
        this.numGeneralRegBlockProb = 0;
        this.numReqBlockByFragmentation = 0;
        this.numReqBlockByLackTransmitters = 0;
        this.numReqBlockByLackReceivers = 0;
        this.numRegBlockByQoTN = 0;
        this.numRegBlockByQoTO = 0;
        this.numRegBlockByOther = 0;
        this.numRegBlockByXt = 0;
        this.numRegBlockByXtOther = 0;
        
        this.numAttemptsCounter = 0;
        this.numAttemptsQoTOCounter = 0;
        
        this.maxCoresByLinks = 0;
        this.numReqGenPerCore = new HashMap<>();
        this.numBlockPerCore = new HashMap<>();
        
        this.numReqGenBW = new HashMap<>();
        this.numReqBlockBW = new HashMap<>();
        
        this.numReqGenPair = new HashMap<>();
        this.numReqBlockPair = new HashMap<>();
        
        this.numReqGenPairBW = new HashMap<>();
        this.numReqBlockPairBW = new HashMap<>();

		this.resultManager = new BlockingProbResultManager();
    }

    /**
     * Adds a new observation of block or not a request
     *
     * @param cp ControlPlane
     * @param success boolean
     * @param request RequestForConnection
     */
    public void addNewObservation(ControlPlane cp, boolean success, RequestForConnection request) {
    	
    	StringBuilder sbPair = new StringBuilder();
		sbPair.append(request.getPair().getSource().getName());
		sbPair.append(SEP);
		sbPair.append(request.getPair().getDestination().getName());
		String pairName = sbPair.toString();
    	
        // Increment generated general requisitions
        this.numGeneralGeneratedReq++;
        
        if(maxCoresByLinks == 0) {
        	maxCoresByLinks = cp.getMesh().maximumCoresByLinks();
        	
        	for(Integer core = 0; core < maxCoresByLinks; core++) {
        		this.numBlockPerCore.put(core, 0);
        	}
        }

        // Increment requests generated by pair
        Integer numReq = this.numReqGenPair.get(pairName);
        if (numReq == null) numReq = 0;
        this.numReqGenPair.put(pairName, numReq + 1);

        // Increment requests generated per bandwidth
        numReq = this.numReqGenBW.get(request.getRequiredBitRate());
        if (numReq == null) numReq = 0;
        this.numReqGenBW.put(request.getRequiredBitRate(), numReq + 1);

        // Increment requests generated by pair / BandWidth
        HashMap<Double, Integer> gplb = this.numReqGenPairBW.get(pairName);
        if (gplb == null) {
            gplb = new HashMap<>();
            this.numReqGenPairBW.put(pairName, gplb);
        }
        numReq = gplb.get(request.getRequiredBitRate());
        if (numReq == null) numReq = 0;
        gplb.put(request.getRequiredBitRate(), numReq + 1);
        
        // Increment requests generated by core
        for (Circuit c: request.getCircuits()) {
	        Integer numReqCore = this.numReqGenPerCore.get(c.getIndexCore());
	        if (numReqCore == null) numReqCore = 0;
	        this.numReqGenPerCore.put(c.getIndexCore(), numReqCore + 1);
        }

        // If the request was blocked
        if (!success) {
            // Increment blocked requests general
            this.numGeneralRegBlockProb++;
            
            for (Circuit c: request.getCircuits()) {
                if(c.isWasBlocked()){ //considers that only one circuit has been blocked
                    switch(c.getBlockCause()){
                        case Circuit.BY_LACK_TX:
                            this.numReqBlockByLackTransmitters++;
                            break;
                        case Circuit.BY_LACK_RX:
                            this.numReqBlockByLackReceivers++;
                            break;
                        case Circuit.BY_XTN:
							this.numRegBlockByXt++;
							break;
                        case Circuit.BY_QOTN:
                            this.numRegBlockByQoTN++;
                            break;
                        case Circuit.BY_XTO:
							this.numRegBlockByXtOther++;
							break;
                        case Circuit.BY_QOTO:
                            this.numRegBlockByQoTO++;
                            break;
                        case Circuit.BY_FRAGMENTATION:
                            this.numReqBlockByFragmentation++;
                            break;
                        case Circuit.BY_OTHER:
                            this.numRegBlockByOther++;
                            break;
                    }
                    break;
                }
            }
            
            for (Circuit c: request.getCircuits()) {
                if(c.isWasBlocked()){ //considers that only one circuit has been blocked
                	
                	// Increment circuits blocked per core
                    Integer numBlockCore = this.numBlockPerCore.get(c.getIndexCore());
                    if (numBlockCore == null) numBlockCore = 0;
                    this.numBlockPerCore.put(c.getIndexCore(), numBlockCore + 1);
                    
                    break;
                }
            }
            
            // Increase requests blocked by pair
            Integer numBlock = this.numReqBlockPair.get(pairName);
            if (numBlock == null) numBlock = 0;
            this.numReqBlockPair.put(pairName, numBlock + 1);
            
            // Increase requests blocked by bitRate
            numBlock = this.numReqBlockBW.get(request.getRequiredBitRate());
            if (numBlock == null) numBlock = 0;
            this.numReqBlockBW.put(request.getRequiredBitRate(), numBlock + 1);
            
            // Increase request blocked by pair / bandwidth
            HashMap<Double, Integer> bplb = this.numReqBlockPairBW.get(pairName);
            if (bplb == null) {
                bplb = new HashMap<>();
                this.numReqBlockPairBW.put(pairName, bplb);
            }
            numBlock = bplb.get(request.getRequiredBitRate());
            if (numBlock == null) numBlock = 0;
            bplb.put(request.getRequiredBitRate(), numBlock + 1);
        }
        
        // If the request has been established
        if (success) {
        	
        	if (cp.getPowerAssignment() instanceof PABSAlgorithm) {
        		int numAttCounter = ((PABSAlgorithm)cp.getPowerAssignment()).getNumAttemptsCounter();
        		if (numAttCounter > this.numAttemptsCounter) {
        			this.numAttemptsCounter = numAttCounter;
            	}
        		
        		int numAttQoTOCounter = ((PABSAlgorithm)cp.getPowerAssignment()).getNumAttemptsQoTOCounter();
        		if (numAttQoTOCounter > this.numAttemptsQoTOCounter) {
        			this.numAttemptsQoTOCounter = numAttQoTOCounter;
            	}
        	} else if (cp.getPowerAssignment() instanceof PABSAlgorithm_v2) {
        		int numAttCounter = ((PABSAlgorithm_v2)cp.getPowerAssignment()).getNumAttemptsCounter();
        		if (numAttCounter > this.numAttemptsCounter) {
        			this.numAttemptsCounter = numAttCounter;
            	}
        		
        		int numAttQoTOCounter = ((PABSAlgorithm_v2)cp.getPowerAssignment()).getNumAttemptsQoTOCounter();
        		if (numAttQoTOCounter > this.numAttemptsQoTOCounter) {
        			this.numAttemptsQoTOCounter = numAttQoTOCounter;
            	}
        	}
        }
    }

    @Override
    public String getFileName() {
        return SimulationRequest.Result.FILE_BLOCKING_PROBABILITY;
    }

    /**
     * Returns the overall blocking probability on the network
     *
     * @return double
     */
    public double getGeneralBlockProb() {
        return ((double) this.numGeneralRegBlockProb / (double) this.numGeneralGeneratedReq);
    }

    /**
     * Returns the blocking probability due to fragmentation
     *
     * @return double
     */
    public double getBlockProbByFragmentation() {
        return ((double) this.numReqBlockByFragmentation / (double) this.numGeneralGeneratedReq);
    }

    /**
     * Returns the blocking probability due to lack of transmitters
     *
     * @return double
     */
    public double getReqBlockByLackTx() {
        return ((double) this.numReqBlockByLackTransmitters / (double) this.numGeneralGeneratedReq);
    }

    /**
     * Returns the blocking probability due to lack of receivers
     *
     * @return double
     */
    public double getReqBlockByLackRx() {
        return ((double) this.numReqBlockByLackReceivers / (double) this.numGeneralGeneratedReq);
    }
    
    
    /**
     * Returns the probability of blocking by QoTN
     *
     * @return double
     */
    public double getRegBlockByQoTN() {
        return ((double) this.numRegBlockByQoTN / (double) this.numGeneralGeneratedReq);
    }
    
    /**
     * Returns the probability of blocking by QoTO
     *
     * @return double
     */
    public double getRegBlockByQoTO() {
        return ((double) this.numRegBlockByQoTO / (double) this.numGeneralGeneratedReq);
    }
    
    /**
     * Returns the probability of blocking by other
     *
     * @return double
     */
    public double getRegBlockByOther() {
        return ((double) this.numRegBlockByOther / (double) this.numGeneralGeneratedReq);
    }
    
    /**
     * Returns the probability of blocking by Crosstalk
     *
     * @return double
     */
    public double getRegBlockByXt() {
        return ((double) this.numRegBlockByXt / (double) this.numGeneralGeneratedReq);
    }
    
    /**
     * Returns the probability of blocking by Crosstalk in Others
     *
     * @return double
     */
    public double getRegBlockByXtOther() {
        return ((double) this.numRegBlockByXtOther / (double) this.numGeneralGeneratedReq);
    }
    
    /**
     * Returns the probability of blocking a given pair
     *
     * @return double
     */
    public double getProbBlockPair(Pair p) {
        double res;

        String source = p.getSource().getName();
        String destination = p.getDestination().getName();
        Integer gen = this.numReqGenPair.get(source + SEP + destination);
        if (gen == null)
            return 0.0; // No requests generated for this pair

        Integer block = this.numReqBlockPair.get(source + SEP + destination);
        if (block == null)
            block = 0;

        res = ((double) block / (double) gen);

        return res;
    }

    /**
     * Returns the blocking probability of a given bitRate
     *
     * @param bw double
     * @return double
     */
    public double getProbBlockBitRate(double bw) {
        double res;
        Integer gen = this.numReqGenBW.get(bw);
        if (gen == null)
            return 0.0; // No requests generated for this pair

        Integer block = this.numReqBlockBW.get(bw);
        if (block == null)
            block = 0;

        res = ((double) block / (double) gen);

        return res;
    }

    /**
     * Returns the blocking probability of a given bitRate in a given pair
     *
     * @param bw double
     * @return double
     */
    public double getProbBlockPairBitRate(Pair p, double bw) {
        double res;
        String source = p.getSource().getName();
        String destination = p.getDestination().getName();
        
        Integer gen = null;
        if(this.numReqGenPairBW.get(source + SEP + destination) != null){
        	gen = this.numReqGenPairBW.get(source + SEP + destination).get(bw);
        }
        
        if(gen == null) return 0.0; // No requests generated for this pair and bitRate
        Integer block = 0;

        HashMap<Double, Integer> hashAux = this.numReqBlockPairBW.get(source + SEP + destination);
        if (hashAux == null || hashAux.get(bw) == null) {
            block = 0;
        } else {
            block = hashAux.get(bw);
        }

        res = ((double) block / (double) gen);

        return res;
    }
    
    /**
     * Returns the probability of blocking per core
     * 
     * @param core
     * @return double
     */
    public double getProbBlockPerCore(Integer core) {
    	double res;
    	
    	Integer gen = this.numReqGenPerCore.get(core);
    	if(gen == null)
    		return 0.0; // No requests generated for this core
    	
    	Integer block = this.numBlockPerCore.get(core);
    	if(block == null)
    		block = 0;
    	
    	res = ((double) block / (double) gen);
    	
    	return res;
    }
    
    /**
     * Returns the util
     * 
     * @return util
     */
    public Util getUtil() {
        return util;
    }
    
    /**
     * Returns the maximum number of cores between all links
     *
     * @return int
     */
    public int getMaxCoresByLinks() {
    	return maxCoresByLinks;
    }
    
    /**
     * Returns the numAttemptsCounter
     * 
     * @return int
     */
	public int getNumAttemptsCounter() {
		return numAttemptsCounter;
	}
	
	/**
	 * Returns the numAttemptsQoTOCounter
	 * 
	 * @return int
	 */
	public int getNumAttemptsQoTOCounter() {
		return numAttemptsQoTOCounter;
	}

}
